version: "3.9"
services:
  app:
    container_name: app
    build:
      context: "./"
    entrypoint: ./main
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080


  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=marketplace

